export const BANCOS_BRASIL = [
  { codigo: "001", nome: "Banco do Brasil" },
  { codigo: "033", nome: "Santander" },
  { codigo: "104", nome: "Caixa Econômica Federal" },
  { codigo: "237", nome: "Bradesco" },
  { codigo: "341", nome: "Itaú Unibanco" },
  { codigo: "260", nome: "Nubank" },
  { codigo: "077", nome: "Inter" },
  { codigo: "336", nome: "C6 Bank" },
  { codigo: "212", nome: "Banco Original" },
  { codigo: "422", nome: "Safra" },
  { codigo: "655", nome: "Neon" },
  { codigo: "290", nome: "PagBank" },
  { codigo: "380", nome: "PicPay" },
  { codigo: "323", nome: "Mercado Pago" },
  { codigo: "756", nome: "Sicoob" },
  { codigo: "748", nome: "Sicredi" },
  { codigo: "136", nome: "Unicred" },
  { codigo: "021", nome: "Banestes" },
  { codigo: "041", nome: "Banrisul" },
  { codigo: "070", nome: "BRB" },
  { codigo: "085", nome: "Ailos" },
  { codigo: "133", nome: "Cresol" },
  { codigo: "197", nome: "Stone" },
  { codigo: "403", nome: "Cora" },
  { codigo: "332", nome: "Acesso" },
  { codigo: "280", nome: "Will Bank" },
  { codigo: "102", nome: "XP" },
  { codigo: "218", nome: "BS2" },
  { codigo: "208", nome: "BTG Pactual" },
  { codigo: "746", nome: "Modal" },
  { codigo: "623", nome: "Banco Pan" },
  { codigo: "069", nome: "Crefisa" },
  { codigo: "389", nome: "Mercantil do Brasil" },
  { codigo: "707", nome: "Daycoval" },
  { codigo: "743", nome: "Semear" },
  { codigo: "633", nome: "Rendimento" },
  { codigo: "037", nome: "Banco do Estado do Pará" },
  { codigo: "084", nome: "Uniprime" },
  { codigo: "074", nome: "Safra" },
  { codigo: "739", nome: "Cetelem" },
  { codigo: "999", nome: "Outro" },
];

export const TIPOS_CONTA = [
  { value: "corrente", label: "Conta Corrente" },
  { value: "poupanca", label: "Conta Poupança" },
];
