export const MCC_ABECS = [
  // Alimentação
  { code: "5411", description: "Supermercados e Mercearias" },
  { code: "5812", description: "Restaurantes" },
  { code: "5814", description: "Lanchonetes e Fast Food" },
  { code: "5441", description: "Docerias e Confeitarias" },
  { code: "5462", description: "Padarias" },
  { code: "5499", description: "Lojas de Alimentos Diversos" },
  { code: "5451", description: "Açougues" },
  { code: "5813", description: "Bares e Casas Noturnas" },
  
  // Varejo
  { code: "5541", description: "Postos de Combustíveis" },
  { code: "5912", description: "Farmácias e Drogarias" },
  { code: "5651", description: "Lojas de Roupas" },
  { code: "5611", description: "Sapatarias" },
  { code: "5311", description: "Lojas de Departamentos" },
  { code: "5331", description: "Lojas de Variedades" },
  { code: "5211", description: "Material de Construção" },
  { code: "5251", description: "Ferragens" },
  { code: "5942", description: "Livrarias" },
  { code: "5944", description: "Joalherias e Relojoarias" },
  { code: "5945", description: "Brinquedos e Jogos" },
  { code: "5946", description: "Artigos Fotográficos" },
  { code: "5947", description: "Presentes e Artigos de Decoração" },
  { code: "5948", description: "Malas e Bolsas" },
  { code: "5949", description: "Lojas de Tecidos e Armarinhos" },
  { code: "5995", description: "Pet Shops e Agropecuárias" },
  { code: "5977", description: "Cosméticos e Perfumarias" },
  { code: "5732", description: "Eletrônicos" },
  { code: "5712", description: "Móveis e Decoração" },
  { code: "5713", description: "Tapetes e Carpetes" },
  { code: "5719", description: "Artigos para Casa" },
  { code: "5722", description: "Eletrodomésticos" },
  { code: "5733", description: "Instrumentos Musicais" },
  { code: "5734", description: "Software e Jogos" },
  { code: "5941", description: "Artigos Esportivos" },
  { code: "5921", description: "Lojas de Bebidas" },
  { code: "5992", description: "Floriculturas" },
  { code: "5993", description: "Tabacarias" },
  
  // Serviços
  { code: "7230", description: "Salões de Beleza e Barbearias" },
  { code: "7941", description: "Academias e Clubes Esportivos" },
  { code: "7298", description: "Clínicas de Estética e Spa" },
  { code: "8011", description: "Médicos e Clínicas" },
  { code: "8021", description: "Dentistas e Ortodontistas" },
  { code: "8031", description: "Osteopatas" },
  { code: "8041", description: "Quiropraxia" },
  { code: "8042", description: "Optometristas e Oftalmologistas" },
  { code: "8049", description: "Podólogos" },
  { code: "8050", description: "Casas de Repouso" },
  { code: "8062", description: "Hospitais" },
  { code: "8099", description: "Serviços Médicos Diversos" },
  { code: "8111", description: "Advogados" },
  { code: "8211", description: "Escolas e Colégios" },
  { code: "8220", description: "Universidades" },
  { code: "8241", description: "Escolas Técnicas" },
  { code: "8244", description: "Cursos de Idiomas" },
  { code: "8299", description: "Serviços Educacionais Diversos" },
  { code: "8398", description: "ONGs e Entidades Beneficentes" },
  { code: "8999", description: "Serviços Profissionais Diversos" },
  
  // Automotivo
  { code: "5511", description: "Concessionárias de Veículos" },
  { code: "5521", description: "Revendas de Veículos Usados" },
  { code: "5531", description: "Autopeças" },
  { code: "5532", description: "Pneus" },
  { code: "5533", description: "Acessórios Automotivos" },
  { code: "5571", description: "Motocicletas" },
  { code: "7531", description: "Funilaria e Pintura" },
  { code: "7534", description: "Borracharias" },
  { code: "7535", description: "Oficinas de Pintura" },
  { code: "7538", description: "Oficinas Mecânicas" },
  { code: "7542", description: "Lava-Rápido" },
  { code: "7549", description: "Guincho e Reboque" },
  
  // Hospedagem e Turismo
  { code: "7011", description: "Hotéis e Pousadas" },
  { code: "4722", description: "Agências de Viagens" },
  { code: "4511", description: "Companhias Aéreas" },
  { code: "4131", description: "Transporte Rodoviário" },
  { code: "4121", description: "Táxis e Transporte Particular" },
  { code: "7512", description: "Locadoras de Veículos" },
  
  // Entretenimento
  { code: "7832", description: "Cinemas" },
  { code: "7911", description: "Casas de Shows e Eventos" },
  { code: "7922", description: "Teatros" },
  { code: "7929", description: "Bandas e Orquestras" },
  { code: "7932", description: "Casas de Bilhar" },
  { code: "7933", description: "Boliches" },
  { code: "7991", description: "Parques de Diversões" },
  { code: "7993", description: "Fliperamas" },
  { code: "7994", description: "Jogos Eletrônicos" },
  { code: "7996", description: "Parques Aquáticos" },
  { code: "7997", description: "Clubes Recreativos" },
  { code: "7999", description: "Recreação e Lazer Diversos" },
  
  // Outros Serviços
  { code: "7211", description: "Lavanderias" },
  { code: "7216", description: "Tinturarias" },
  { code: "7221", description: "Laboratórios Fotográficos" },
  { code: "7251", description: "Conserto de Sapatos" },
  { code: "7261", description: "Serviços Funerários" },
  { code: "7273", description: "Agências de Encontros" },
  { code: "7276", description: "Serviços Tributários" },
  { code: "7277", description: "Serviços de Aconselhamento" },
  { code: "7278", description: "Clubes de Compras" },
  { code: "7296", description: "Aluguel de Roupas" },
  { code: "7311", description: "Agências de Publicidade" },
  { code: "7333", description: "Serviços Gráficos" },
  { code: "7338", description: "Cópias e Reproduções" },
  { code: "7349", description: "Limpeza e Conservação" },
  { code: "7361", description: "Agências de Emprego" },
  { code: "7372", description: "Desenvolvimento de Software" },
  { code: "7375", description: "Serviços de Informação" },
  { code: "7379", description: "Serviços de Informática" },
  { code: "7392", description: "Consultoria Empresarial" },
  { code: "7393", description: "Detetives" },
  { code: "7394", description: "Aluguel de Equipamentos" },
  { code: "7395", description: "Revelação de Fotos" },
  { code: "7399", description: "Serviços Empresariais Diversos" },
  { code: "7622", description: "Conserto de Eletrônicos" },
  { code: "7623", description: "Conserto de Ar Condicionado" },
  { code: "7629", description: "Reparos Elétricos Diversos" },
  { code: "7631", description: "Conserto de Relógios" },
  { code: "7641", description: "Estofamento de Móveis" },
  { code: "7692", description: "Serviços de Solda" },
  { code: "7699", description: "Reparos Diversos" },
  
  // Estacionamento
  { code: "7523", description: "Estacionamentos" },
  
  // Construção
  { code: "1520", description: "Empreiteiras" },
  { code: "1711", description: "Encanadores" },
  { code: "1731", description: "Eletricistas" },
  { code: "1740", description: "Isolamento e Alvenaria" },
  { code: "1750", description: "Carpintaria" },
  { code: "1761", description: "Telhados e Calhas" },
  { code: "1771", description: "Pisos e Revestimentos" },
  { code: "1799", description: "Serviços de Construção Diversos" },
];
